services:
  app:
    build:
      context: ./
      dockerfile: ./../Dockerfile
      args:
        SCRIPT_DIR: "map_timeseries"
    environment:
      LOCALSTACK_URL: "http://localstack:4566"
      MOUNTEBANK_URL: "http://mountebank:2525"
      S3_BUCKET: "fake"
      WHO_URL: "https://frontdoor-l4uikgap6gz3m.azurefd.net/MPX/V_MPX_VALIDATED_DAILY"
      AWS_ACCESS_KEY_ID: "fake"
      AWS_SECRET_ACCESS_KEY: "fake"
      DB_CONNECTION: "mongodb://mongo:27017"
      DATABASE_NAME: "monkeypox"
  localstack:
    image: localstack/localstack
    environment:
      AWS_ACCESS_KEY_ID: "fake"
      AWS_SECRET_ACCESS_KEY: "fake"
      SERVICES: "s3"
      DOCKER_HOST: "unix:///var/run/docker.sock"
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - "4566:4566"            # LocalStack Gateway
      - "4510-4559:4510-4559"  # external services port range
  mountebank:
    image: jkris/mountebank
    ports:
      - "2525:2525"  # Mountebank port
      - "4545:4545"  # Imposter port
  mongo:
    image: mongo:5.0.12
    restart: always
    init: true
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: "monkeypox"
