services:
  test:
    build:
      context: ./
      dockerfile: "Dockerfile-test"
    environment:
      LOCALSTACK_URL: "http://localstack:4566"
      S3_BUCKET: "fake"
      AWS_ACCESS_KEY_ID: "fake"
      AWS_SECRET_ACCESS_KEY: "fake"
  localstack:
    image: localstack/localstack
    environment:
      AWS_ACCESS_KEY_ID: "fake"
      AWS_SECRET_ACCESS_KEY: "fake"
      SERVICES: "s3"
      DOCKER_HOST: "unix:///var/run/docker.sock"
      START_WEB: 0  # https://github.com/localstack/localstack/issues/1466#issuecomment-599822542
      HOSTNAME: "localhost"
      EAGER_SERVICE_LOADING: 1
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - "4566:4566"            # LocalStack Gateway
      - "4510-4559:4510-4559"  # external services port range
