# 3.10 not yet available
FROM public.ecr.aws/lambda/python:3.9
COPY . ${LAMBDA_TASK_ROOT}
COPY requirements.txt .

RUN /var/lang/bin/python3.9 -m pip install --upgrade pip
RUN pip3 install -r requirements.txt --target "${LAMBDA_TASK_ROOT}"

CMD ["run.handler"]
