name: Monkeypox data comparison script deploy

on:
  push:
    branches: [main]
    paths:
      - 'scripts/cdc_who_gh_comparison/*.py'
      - 'scripts/cdc_who_gh_comparison/pyproject.toml'
      - 'scripts/cdc_who_gh_comparison/poetry.lock'
      - 'scripts/Dockerfile-test'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR (latest)
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        REPO: monkeypox_agency_comparison
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $REGISTRY/$REPO:$IMAGE_TAG -t $REGISTRY/$REPO .
        docker push $REGISTRY/$REPO:$IMAGE_TAG
        docker push $REGISTRY/$REPO:latest
