# This transfers files from S3 to Github.
# TODO: incorporate into the script in this repo
# blocked by https://github.com/github/rest-api-description/issues/1147
name: Monkeypox data S3 -> Github

on:
  schedule:
    - cron: '10 19 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: voxmedia/github-action-slack-notify-build@v1
      with:
        channel: monkeypox-bots
        status: STARTED
        color: good
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
    - uses: actions/checkout@v2
    - name: Download latest.csv file from S3
      uses: keithweaver/aws-s3-github-action@v1.0.0
      with:
        command: cp
        source: s3://${{ secrets.S3_BUCKET }}/latest.csv
        destination: ./bucket/latest.csv
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: eu-central-1
    - name: Upload files to GitHub
      run: |
        git pull
        sudo mv bucket/latest.csv .
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add latest.csv 
        git commit -m "Updating latest.csv" || echo "Nothing changed since last run."
        git push
    - name: Download cdc_latest.csv file from S3
      uses: keithweaver/aws-s3-github-action@v1.0.0
      with:
        command: cp
        source: s3://${{ secrets.S3_BUCKET }}/cdc_latest.csv
        destination: ./bucket/cdc_latest.csv
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: eu-central-1
    - name: Upload files to GitHub
      run: |
        git pull
        sudo mv bucket/cdc_latest.csv .
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add cdc_latest.csv
        git commit -m "Updating cdc_latest.csv" || echo "Nothing changed since last run."
        git push
    - name: Download who_latest.csv file from S3
      uses: keithweaver/aws-s3-github-action@v1.0.0
      with:
        command: cp
        source: s3://${{ secrets.S3_BUCKET }}/who_latest.csv
        destination: ./bucket/who_latest.csv
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: eu-central-1
    - name: Upload files to GitHub
      run: |
        git pull
        sudo mv bucket/who_latest.csv .
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add who_latest.csv
        git commit -m "Updating who_latest.csv" || echo "Nothing changed since last run."
        git push
    - name: Notify slack success
      if: success()
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
      uses: voxmedia/github-action-slack-notify-build@v1
      with:
        # Updates existing message from the first step
        message_id: ${{ steps.slack.outputs.message_id }}
        channel: monkeypox-bots
        status: SUCCESS
        color: good
    - name: Notify slack failure
      if: failure()
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
      uses: voxmedia/github-action-slack-notify-build@v1
      with:
        # Updates existing message from the first step
        message_id: ${{ steps.slack.outputs.message_id }}
        channel: monkeypox-bots
        status: FAILURE
        color: danger
