name: Test data frontend

on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/data_tests.yml'
      - 'data/*.py'
      - 'data/pyproject.toml'
      - 'data/poetry.lock'
      - 'data/Dockerfile-test'
  pull_request:
    paths:
      - '.github/workflows/data_tests.yml'
      - 'data/*.py'
      - 'data/pyproject.toml'
      - 'data/poetry.lock'
      - 'data/Dockerfile-test'
 
 
jobs:
  tests:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Run tests
        run: cd data && ./test_stack.sh
