name: Test map timeseries generation scripts

on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/map_timeseries_tests.yml'
      - 'scripts/map_timeseries/*.py'
      - 'scripts/map_timeseries/pyproject.toml'
      - 'scripts/map_timeseries/poetry.lock'
      - 'scripts/Dockerfile-test'
  pull_request:
    paths:
      - '.github/workflows/map_timeseries_tests.yml'
      - 'scripts/map_timeseries/*.py'
      - 'scripts/map_timeseries/pyproject.toml'
      - 'scripts/map_timeseries/poetry.lock'
      - 'scripts/Dockerfile-test'


jobs:
  tests:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Run tests
        run: cd scripts/map_timeseries && ./test_stack.sh
