services:
  app:
    build:
      context: ./
      dockerfile: ./../Dockerfile-R
      args:
        SCRIPT_DIR: "reidentification_risk"
    environment:
      LOCALSTACK_URL: "http://localstack:4566"
      MOUNTEBANK_URL: "http://mountebank:2525"
      SLACK_WEBHOOK_URL: "http://mountebank:4545"
      S3_BUCKET: "fake"
      AWS_ACCESS_KEY_ID: "fake"
      AWS_SECRET_ACCESS_KEY: "fake"
  localstack:
    image: localstack/localstack
    environment:
      AWS_ACCESS_KEY_ID: "fake"
      AWS_SECRET_ACCESS_KEY: "fake"
      SERVICES: "s3"
      DOCKER_HOST: "unix:///var/run/docker.sock"
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - "4566:4566"            # LocalStack Gateway
      - "4510-4559:4510-4559"  # external services port range
  mountebank:
    image: jkris/mountebank
    ports:
      - "2525:2525"  # Mountebank port
      - "4545:4545"  # Imposter port
